name: build flutter app release

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.vscode/**'
      - 'docs/**'
  workflow_dispatch:

jobs:
  build-ios:
    name: Build Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/.gradle/caches
            ~/.gradle/wrapper
            example/.dart_tool
            example/build
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install dependencies
        run: |
          cd example/
          flutter pub get

      - name: Ensure gradle wrapper is compatible
        run: |
          sed -i.bak 's/distributionUrl=https\:\/\/services.gradle.org\/distributions\/gradle-.*-all.zip/distributionUrl=https\:\/\/services.gradle.org\/distributions\/gradle-7.6.3-all.zip/' example/android/gradle/wrapper/gradle-wrapper.properties

      - name: Build Android APK
        run: |
          cd example/
          flutter build apk --release

      - name: Build iOS IPA
        run: |
          cd example/ios/
          pod repo update
          cd ..
          flutter build ios --release --no-codesign

      - name: Package iOS IPA
        working-directory: example/build/ios/iphoneos
        run: |
          mkdir Payload
          mv Runner.app Payload/
          zip -r FlutterIpaExport.ipa Payload

      - name: Upload Android APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: example/build/app/outputs/flutter-apk/app-release.apk

      - name: Rename APK
        run: |
          mkdir -p release
          APK_PATH=$(find example/build/app/outputs/flutter-apk/*.apk)
          mv $APK_PATH example/build/app/outputs/flutter-apk/app-${{ github.sha }}-$(date +'%Y-%m-%d').apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Git Tag
        id: tag
        run: |
          TAG_NAME="FlutterTailWind-v$(date +'%Y-%m-%d-%H')"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag $TAG_NAME
          git push https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git $TAG_NAME

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: |
            example/build/app/outputs/flutter-apk/*.apk
            example/build/ios/iphoneos/FlutterIpaExport.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}